	<?php
	$club_rank["Europe"] = [
	array("rank"=>1, "name"=>"England"),
	array("rank"=>2, "name"=>"Spain"),
	array("rank"=>3, "name"=>"Italy"),
	array("rank"=>4, "name"=>"Germany"),
	array("rank"=>5, "name"=>"France"),
	array("rank"=>6, "name"=>"Portugal"),
	array("rank"=>7, "name"=>"Netherlands"),
	array("rank"=>8, "name"=>"Austria"),
	array("rank"=>9, "name"=>"Scotland"),
	array("rank"=>10, "name"=>"Russia"),
	array("rank"=>11, "name"=>"Serbia"),
	array("rank"=>12, "name"=>"Ukraine"),
	array("rank"=>13, "name"=>"Belgium"),
	array("rank"=>14, "name"=>"Switzerland"),
	array("rank"=>15, "name"=>"Greece"),
	array("rank"=>16, "name"=>"Czech"),
	array("rank"=>17, "name"=>"Norway"),
	array("rank"=>18, "name"=>"Denmark"),
	array("rank"=>19, "name"=>"Croatia"),
	array("rank"=>20, "name"=>"Turkey"),
	array("rank"=>21, "name"=>"Cyprus"),
	array("rank"=>22, "name"=>"Israel"),
	array("rank"=>23, "name"=>"Sweden"),
	array("rank"=>24, "name"=>"Bulgaria"),
	array("rank"=>25, "name"=>"Romania"),
	array("rank"=>26, "name"=>"Azerbaijan"),
	array("rank"=>27, "name"=>"Hungary"),
	array("rank"=>28, "name"=>"Poland"),
	array("rank"=>29, "name"=>"Kazakhstan"),
	array("rank"=>30, "name"=>"Slovakia"),
	array("rank"=>31, "name"=>"Slovenia"),
	array("rank"=>32, "name"=>"Belarus"),
	array("rank"=>33, "name"=>"Moldova"),
	array("rank"=>34, "name"=>"Lithuania"),
	array("rank"=>35, "name"=>"Bosnia and Herzegovina"),
	array("rank"=>36, "name"=>"Finland"),
	array("rank"=>37, "name"=>"Luxembourg"),
	array("rank"=>38, "name"=>"Latvia"),
	array("rank"=>39, "name"=>"Kosovo"),
	array("rank"=>40, "name"=>"Ireland"),
	array("rank"=>41, "name"=>"Armenia"),
	array("rank"=>42, "name"=>"North Ireland"),
	array("rank"=>43, "name"=>"Albania"),
	array("rank"=>44, "name"=>"Faroe Islands"),
	array("rank"=>45, "name"=>"Estonia"),
	array("rank"=>46, "name"=>"Malta"),
	array("rank"=>47, "name"=>"Georgia"),
	array("rank"=>48, "name"=>"Macedonia"),
	array("rank"=>49, "name"=>"Liechtenstein"),
	array("rank"=>50, "name"=>"Wales"),
	array("rank"=>51, "name"=>"Gibraltar"),
	array("rank"=>52, "name"=>"Iceland"),
	array("rank"=>53, "name"=>"Montenegro"),
	array("rank"=>54, "name"=>"Andorra"),
	array("rank"=>55, "name"=>"San Marino")];

	$club_rank["South America"] = [
	array("rank"=>1, "name"=>"Brazil"),
	array("rank"=>2, "name"=>"Argentina"),
	array("rank"=>3, "name"=>"Paraguay"),
	array("rank"=>4, "name"=>"Ecuador"),
	array("rank"=>5, "name"=>"Colombia"),
	array("rank"=>6, "name"=>"Uruguay"),
	array("rank"=>7, "name"=>"Chile"),
	array("rank"=>8, "name"=>"Bolivia"),
	array("rank"=>9, "name"=>"Venezuela"),
	array("rank"=>10, "name"=>"Peru")];

	$club_rank["North America"] = [
	array("rank"=>1, "name"=>"Mexico"),
	array("rank"=>2, "name"=>"USA"),
	array("rank"=>3, "name"=>"Honduras"),
	array("rank"=>4, "name"=>"Costa Rica"),
	array("rank"=>5, "name"=>"Guatemala"),
	array("rank"=>6, "name"=>"Panama"),
	array("rank"=>7, "name"=>"Canada"),
	array("rank"=>8, "name"=>"Salvador"),
	array("rank"=>9, "name"=>"Haiti"),
	array("rank"=>10, "name"=>"Dominica"),
	array("rank"=>11, "name"=>"Nicaragua"),
	array("rank"=>12, "name"=>"Jamaica"),
	array("rank"=>13, "name"=>"Suriname"),
	array("rank"=>14, "name"=>"Trinidad and Tobago"),
	array("rank"=>15, "name"=>"Curacao"),
	array("rank"=>16, "name"=>"Belize"),
	array("rank"=>17, "name"=>"Martinique")];

	$club_rank["Asia"] = [
	array("rank"=>1, "name"=>"Saudi Arabia"),
	array("rank"=>2, "name"=>"Japan"),
	array("rank"=>3, "name"=>"South Korea"),
	array("rank"=>4, "name"=>"Uzbekistan"),
	array("rank"=>5, "name"=>"Iran"),
	array("rank"=>6, "name"=>"Qatar"),
	array("rank"=>7, "name"=>"Hongkong"),
	array("rank"=>8, "name"=>"United Arab Emirates"),
	array("rank"=>9, "name"=>"Jordan"),
	array("rank"=>10, "name"=>"Malaysia"),
	array("rank"=>11, "name"=>"Thailand"),
	array("rank"=>12, "name"=>"Vietnam"),
	array("rank"=>13, "name"=>"Tajikistan"),
	array("rank"=>14, "name"=>"Iraq"),
	array("rank"=>15, "name"=>"China"),
	array("rank"=>16, "name"=>"India"),
	array("rank"=>17, "name"=>"Turkmenistan"),
	array("rank"=>18, "name"=>"Singapore")];

	$club_rank["Africa"] = [
	array("rank"=>1, "name"=>"Morocco"),
	array("rank"=>2, "name"=>"Egypt"),
	array("rank"=>3, "name"=>"Algeria"),
	array("rank"=>4, "name"=>"Tunisia"),
	array("rank"=>5, "name"=>"South Africa"),
	array("rank"=>6, "name"=>"DR Congo"),
	array("rank"=>7, "name"=>"Angola"),
	array("rank"=>8, "name"=>"Sudan"),
	array("rank"=>9, "name"=>"Libya"),
	array("rank"=>10, "name"=>"Guinea"),
	array("rank"=>11, "name"=>"Tanzania"),
	array("rank"=>12, "name"=>"Nigeria"),
	array("rank"=>13, "name"=>"Zambia"),
	array("rank"=>14, "name"=>"Cameroon")];

	$club_rank["Oceania"] = [];
	?>
